"""chatbot messages table

Revision ID: e72ec282848c
Revises: 09de8957ab36
Create Date: 2026-07-29 15:19:12.311628
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e72ec282848c'
down_revision: str | None = '09de8957ab36'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='chatbot_message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chatbot_messages_user_created', 'chatbot_messages', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chatbot_messages_user_created', table_name='chatbot_messages')
    op.drop_table('chatbot_messages')
    # ### end Alembic commands ###
    # `drop_table` leaves the enum type behind in PostgreSQL — drop it too so the
    # downgrade is a clean round-trip and a re-upgrade can recreate it.
    sa.Enum(name='chatbot_message_role').drop(op.get_bind(), checkfirst=True)
