"""citizen documents: fraud analysis columns

Revision ID: 6c3214e4ab74
Revises: 3bf29fdd1f9c
Create Date: 2026-07-23 10:50:21.854055
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6c3214e4ab74'
down_revision: str | None = '3bf29fdd1f9c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_documents', sa.Column('fraud_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('application_documents', sa.Column('fraud_risk', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_documents', 'fraud_risk')
    op.drop_column('application_documents', 'fraud_analysis')
    # ### end Alembic commands ###
