"""citizen documents: applications, documents, checklist

Revision ID: 3bf29fdd1f9c
Revises: 3f189c6664e4
Create Date: 2026-07-23 09:32:06.810410
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3bf29fdd1f9c'
down_revision: str | None = '3f189c6664e4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('citizen_id', sa.String(length=64), nullable=True),
    sa.Column('service_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('incomplete', 'complete', name='application_status'), nullable=False),
    sa.Column('checklist_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('application_id', sa.String(length=64), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('stored_path', sa.String(length=512), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('uploading', 'analysing', 'validated', 'rejected', name='app_document_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('extraction_method', sa.Enum('native_pdf', 'mistral_ocr', name='extraction_method'), nullable=True),
    sa.Column('extracted_text_preview', sa.Text(), nullable=True),
    sa.Column('classification', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('classification_error', sa.Text(), nullable=True),
    sa.Column('matched_checklist_item_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_documents_application_id'), 'application_documents', ['application_id'], unique=False)
    op.create_table('checklist_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('application_id', sa.String(length=64), nullable=False),
    sa.Column('item_key', sa.String(length=64), nullable=False),
    sa.Column('libelle', sa.String(length=255), nullable=False),
    sa.Column('categorie', sa.Enum('identite', 'ressources', 'logement', 'famille', 'autre', name='document_category'), nullable=False),
    sa.Column('obligatoire', sa.Boolean(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('formats_acceptes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_items_application_id'), 'checklist_items', ['application_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checklist_items_application_id'), table_name='checklist_items')
    op.drop_table('checklist_items')
    op.drop_index(op.f('ix_application_documents_application_id'), table_name='application_documents')
    op.drop_table('application_documents')
    op.drop_table('applications')
    # ### end Alembic commands ###
