"""application document content hash

Revision ID: 86810737c9ce
Revises: e5f6a7b8c9d0
Create Date: 2026-07-27 17:58:38.600868
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '86810737c9ce'
down_revision: str | None = 'e5f6a7b8c9d0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_documents', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_application_documents_content_hash'), 'application_documents', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_documents_content_hash'), table_name='application_documents')
    op.drop_column('application_documents', 'content_hash')
    # ### end Alembic commands ###
