"""checklist profile hash for mistral-backed generation

Revision ID: 09de8957ab36
Revises: 86810737c9ce
Create Date: 2026-07-27 22:29:45.270158
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '09de8957ab36'
down_revision: str | None = '86810737c9ce'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('checklist_profile_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'checklist_profile_hash')
    # ### end Alembic commands ###
