"""initial schema

Revision ID: 3f189c6664e4
Revises: 
Create Date: 2026-07-22 16:54:36.420252
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3f189c6664e4'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citizens',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('social_security_number', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cases',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('application_number', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('submitted', 'awaiting_documents', 'under_review', 'ready_for_decision', 'validated', 'rejected', name='case_status'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('citizen_id', sa.String(length=64), nullable=False),
    sa.Column('service_id', sa.String(length=64), nullable=False),
    sa.Column('service_label', sa.String(length=255), nullable=False),
    sa.Column('score_value', sa.Integer(), nullable=True),
    sa.Column('score_band', sa.Enum('high', 'medium', 'low', name='case_score_band'), nullable=True),
    sa.Column('score_computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score_model', sa.String(length=120), nullable=True),
    sa.Column('marital_status', sa.Enum('single', 'married', 'pacs', 'cohabiting', name='marital_status'), nullable=False),
    sa.Column('dependent_children', sa.Integer(), nullable=False),
    sa.Column('attached_adults', sa.Integer(), nullable=False),
    sa.Column('occupancy_status', sa.Enum('tenant', 'owner', 'hosted', name='occupancy_status'), nullable=False),
    sa.Column('living_area_sqm', sa.Integer(), nullable=False),
    sa.Column('monthly_rent_excluding_charges', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('postal_code', sa.String(length=16), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('annual_income', sa.Integer(), nullable=False),
    sa.Column('profile_captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_number')
    )
    op.create_index('ix_cases_citizen_id', 'cases', ['citizen_id'], unique=False)
    op.create_index('ix_cases_status_submitted_at', 'cases', ['status', 'submitted_at'], unique=False)
    op.create_table('case_decisions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.Enum('validated', 'rejected', name='decision_outcome'), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('decided_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('case_documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('requirement_id', sa.String(length=64), nullable=False),
    sa.Column('requirement_label', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('uploading', 'analysing', 'validated', 'rejected', name='document_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_documents_case_id'), 'case_documents', ['case_id'], unique=False)
    op.create_table('coherence_reports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.Enum('passed', 'warning', 'failed', name='report_outcome'), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('completeness_reports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.Enum('passed', 'warning', 'failed', name='report_outcome'), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completion_rate', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('coherence_anomalies',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('report_id', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'error', name='anomaly_severity'), nullable=False),
    sa.Column('field', sa.String(length=255), nullable=False),
    sa.Column('declared_value', sa.String(length=255), nullable=False),
    sa.Column('observed_value', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['coherence_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coherence_anomalies_report_id'), 'coherence_anomalies', ['report_id'], unique=False)
    op.create_table('completeness_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('report_id', sa.String(length=64), nullable=False),
    sa.Column('item_key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('received', sa.Boolean(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['completeness_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'item_key', name='uq_completeness_item_key')
    )
    op.create_index(op.f('ix_completeness_items_report_id'), 'completeness_items', ['report_id'], unique=False)
    op.create_table('decision_evidence',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('decision_id', sa.String(length=64), nullable=False),
    sa.Column('field', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['case_decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_evidence_decision_id'), 'decision_evidence', ['decision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_evidence_decision_id'), table_name='decision_evidence')
    op.drop_table('decision_evidence')
    op.drop_index(op.f('ix_completeness_items_report_id'), table_name='completeness_items')
    op.drop_table('completeness_items')
    op.drop_index(op.f('ix_coherence_anomalies_report_id'), table_name='coherence_anomalies')
    op.drop_table('coherence_anomalies')
    op.drop_table('completeness_reports')
    op.drop_table('coherence_reports')
    op.drop_index(op.f('ix_case_documents_case_id'), table_name='case_documents')
    op.drop_table('case_documents')
    op.drop_table('case_decisions')
    op.drop_index('ix_cases_status_submitted_at', table_name='cases')
    op.drop_index('ix_cases_citizen_id', table_name='cases')
    op.drop_table('cases')
    op.drop_table('citizens')
    # ### end Alembic commands ###
