"""auth email verification and password reset tokens

Revision ID: b5045295d36c
Revises: b7e1c2d3f4a5
Create Date: 2026-07-24 11:34:34.137686
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b5045295d36c'
down_revision: str | None = 'b7e1c2d3f4a5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.Enum('EMAIL_VERIFICATION', 'PASSWORD_RESET', name='auth_token_purpose'), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auth_tokens_token_hash', 'auth_tokens', ['token_hash'], unique=True)
    op.create_index('ix_auth_tokens_user_purpose', 'auth_tokens', ['user_id', 'purpose'], unique=False)
    # `server_default` is required, not cosmetic: the column is NOT NULL and
    # `users` already has rows, so adding it without one fails outright.
    # Existing accounts predate verification and are therefore unverified —
    # false is the honest backfill, not true-for-convenience.
    #
    # The default is then dropped: it exists only to fill the rows that were
    # already there. New rows get their value from the model, so leaving a
    # database-level default behind would be a second source of truth.
    op.add_column(
        'users',
        sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('users', 'is_verified', server_default=None)
    op.add_column('users', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))


def downgrade() -> None:
    op.drop_column('users', 'verified_at')
    op.drop_column('users', 'is_verified')
    op.drop_index('ix_auth_tokens_user_purpose', table_name='auth_tokens')
    op.drop_index('ix_auth_tokens_token_hash', table_name='auth_tokens')
    op.drop_table('auth_tokens')
    # PostgreSQL keeps an enum type after its last column is dropped, so
    # `drop_table` alone leaves `auth_token_purpose` behind and re-running the
    # upgrade fails with "type already exists". Autogenerate never emits this.
    sa.Enum(name='auth_token_purpose').drop(op.get_bind(), checkfirst=True)
