"""move fraud analysis from application_documents to case_documents

Revision ID: c5021f9aec0d
Revises: 6c3214e4ab74
Create Date: 2026-07-23 11:10:59.816514
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c5021f9aec0d'
down_revision: str | None = '6c3214e4ab74'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_documents', 'fraud_risk')
    op.drop_column('application_documents', 'fraud_analysis')
    op.add_column('case_documents', sa.Column('fraud_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('case_documents', sa.Column('fraud_risk', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_documents', 'fraud_risk')
    op.drop_column('case_documents', 'fraud_analysis')
    op.add_column('application_documents', sa.Column('fraud_analysis', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('application_documents', sa.Column('fraud_risk', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
